"""create review_history table with datetime

Revision ID: 25bf66fb021a
Revises: 475278c8df6b
Create Date: 2025-04-09 19:17:29.825245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bf66fb021a'
down_revision = '475278c8df6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('date_flown', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_history')
    # ### end Alembic commands ###
