"""change date_flown to DateTime

Revision ID: 475278c8df6b
Revises: 
Create Date: 2025-04-09 12:03:59.912895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475278c8df6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_history', schema=None) as batch_op:
        # batch_op.alter_column('date_flown',
        #        existing_type=sa.TEXT(),
        #        type_=sa.DateTime(),
        #        existing_nullable=True)
        batch_op.alter_column('date_flown',
                existing_type=sa.Text(),
                type_=sa.DateTime(),
                postgresql_using='date_flown::timestamp')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_history', schema=None) as batch_op:
        batch_op.alter_column('date_flown',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
